version: '3'

services:
  postgres:
    image: "postgres:15"
    container_name: "postgres"
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=workload
      - POSTGRES_USER=workload
      - POSTGRES_DB=workload
