server:
  address: 127.0.0.1
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workload
    username: workload
    password: workload
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api
  application:
    name: core

springdoc:
  show-actuator: true